### ISSUE TITLE
Remove jade templating?

### ISSUE THREAD

**Issue by alveflo** [victorzki/makiato#21]
@LosGlennos - How about we remove rendering of jade templates on the server side (`res.render('index.jade', settings)`) and just respond with static html files, and rely on templating using Angular? It feels unnecessary to use two different technologies for templating...

Anyway - I think we should keep using Jade to create the html files, but instead of rendering them on each request we compile them with gulp and copy them to `app/public`.

**Comment by LosGlennos** [comment]
Seems like a great way to go about it. I say shoot!

**Comment by alveflo** [comment]
Sweet! Wanna fix? Could be a good way to get to know the gulp system :+1:

**Comment by alveflo** [comment]
I assigned you.. Let me know if you disagree :smile:
